export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CONFIG_HOME:=$HOME/.cache}"
export ZDOTDIR="${ZDOTDIR:=$XDG_CONFIG_HOME/zsh}"
export SCRIPTDIR="${XDG_CONFIG_HOME}/scripts"

#source /etc/profile.d/nix{,-daemon}.sh
source "$ZDOTDIR/.zshenv"

source "$XDG_CONFIG_HOME/homerun/initialize"
